config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: :create
  end

  resources :pharmacies do
    resources :orders, only: [:create]
  end

  resources :medicines, only: :index

  resources :prescriptions, only: [:create]

  resources :orders, only: [:update, :show]

  get 'checkout', to: "pages#checkout", as: :checkout

  get 'profile', to: "pages#view_profile", as: :profile
end

app/models/pharmacy.rb
class Pharmacy < ApplicationRecord
  has_many :stocks
  has_many :medicines, through: :stock
  has_many :orders, dependent: :destroy
  has_many :chatrooms

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/pharmacies_controller.rb
class PharmaciesController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @query = params[:query]
    session[:passed_variable] = @query

    @pharmacies = []
    if params[:query].present?
      @medicines = Medicine.where("name ILIKE ?", "%#{params[:query]}%")
      if @medicines[0].present?
        @stocks = Stock.where("medicine_id = #{@medicines[0].id} AND quantity > 0")
        @stocks.each do |stock|
          @pharmacies << stock.pharmacy
        end
      end
    else
      @pharmacies = Pharmacy.all
    end

    @markers = @pharmacies.map do |pharmacy|
      {
        lat: pharmacy.latitude,
        lng: pharmacy.longitude,
        info_window: render_to_string(partial: "info_window", locals: {pharmacy: pharmacy})
      }
    end
    # raise

    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: "pharmacies/list", locals: {medicines: @medicines}, formats: [:html] }
    end
  end

  def show
    @pharmacy = Pharmacy.find(params[:id])
    @order = Order.new

    @query = session[:passed_variable]
    @medicines = Medicine.where("name ILIKE ?", "%#{@query}%")
    @medicine = Medicine.find(@medicines[0].id)
    # raise
    @medicine_stock = @pharmacy.stocks.where(medicine_id: @medicine)

    # @stock_med = Stock.where(medicine_id: @medicine)
    # @stock_pharma = @stock_med.where(pharmacy_id: @pharmacy)

    if params[:query].present?
      @medicines = Medicine.where("name ILIKE ?", "%#{params[:query]}%")
      # raise
      if @medicines[0].present?
        @stocks = @pharmacy.stocks.where(medicine_id: @medicines[0].id)
      end
    else
      @stocks = @pharmacy.stocks
    end
  end

  def create
    @pharmacy.new(pharmacy_params)
    if @pharmacy.save
      redirect to profile_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  private

  def pharmacy_params
    params.require(:pharmacy).permit(:name, :address, :phone_number, :opening_hours, :user_id)
  end
end

app/views/pharmacies/_info_window.html.erb
<h2><%= pharmacy.name %></h2>
<p><%= pharmacy.address %></p>

app/views/pharmacies/_list.html.erb
<div data-search-drugs-target="list">
  <% if params[:query].present? %>
    <% if @medicines[0].present? %>
    <div class="container-fluid">
      <h2 id="pharma-count"><%= "#{@stocks.count} Pharmacies found" %></h2>
      <% @medicines.each do |medicine| %>
        <div class="desc-card">
          <h3><%= medicine.name %></h3>
          <p>Rs <%= number_with_delimiter(medicine.price, :delimiter => ',') %></p>
          <% if medicine.prescription == true %>
            <p><%= "Prescription needed" %></p>
          <% else %>
            <p><%= "No prescription needed" %></p>
          <% end %>
        </div>
      <% end %>
    </div>
      <hr>

      <div class="container-fluid pharma-cards">
        <% @stocks.each do |stock| %>
          <%= link_to pharmacy_path(stock.pharmacy) do %>
            <div class="card pharma-card mt-3">
              <div class="pharma-card-info">
                <h4><%= stock.pharmacy.name %></h4>
                <p><%= stock.pharmacy.address %></p>
                <p class="pharma-card-hours"><i class="fa-regular fa-clock"></i> 8h - 20h
                <%# <%= stock.pharmacy.opening_hours %>
                </p>
              </div>
              <div class="pharma-card-photo">
                <%= image_tag "https://images.unsplash.com/photo-1622230208995-0f26eba75875?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80", style: "width:150px;" %>
              </div>

            </div>
          <% end %>
        <% end %>
      </div>

    <% else %>
      <p><%= "No results" %></p>
    <% end %>
  <% else %>
    <p><%= "No results" %></p>
  <% end %>
</div>

app/views/pharmacies/index.html.erb
<%# <div data-controller="search-drugs"> %>
  <div class="container-fluid mt-5">
    <div class="form">
      <%= form_with url: pharmacies_path, method: :get, html: {data: {search_drugs_target: "form"}} do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Find your drug",
          data: {search_drugs_target: "input", action: "keyup->search-drugs#autocomplete"}
        %>
        <div class="d-grid gap-2 mt-3">
          <%= submit_tag "Search", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>


  <%= render 'list', medicines: @medicines %>
</div>

<div class="mt-5" style="width: 100%; height: 450px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/pharmacies/show.html.erb
<div>
  <%= link_to pharmacies_path(query: @query) do %>
    <i class="fa-solid fa-arrow-left back"></i>
  <% end %>
</div>
<div class="order-box mb-4">
  <div class="order-content">
    <h4><%= @pharmacy.name %></h4>
    <p><%= "Address: #{@pharmacy.address}" %></p>
  </div>
</div>

<div class="med-cards">
  <div class="card med-card">
    <%= cl_image_tag @medicine.photo.key, class: "med-card-img" %>
    <div>
      <h3><%= @medicine.name %></h3>
      <p class="med-card-price">Rs <%= number_with_delimiter(@medicine.price, :delimiter => ',') %></p>
      In stock: <%= @medicine_stock[0].quantity %>
      <%= simple_form_for([@pharmacy, @order]) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.input :quantity, label: false, collection: 1..@medicine_stock[0].quantity %>
      <%# <%= f.input :delivery %>
      <%= f.hidden_field :medicine_id, value: @medicine.id %>
      <%= f.submit value: "Add to cart", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

<hr>

<h2 id="more">More products from <%= @pharmacy.name %></h2>


<div class="form mt-3">
  <%= form_with url: pharmacy_path(@pharmacy), method: :get, html: {data: {search_drugs_target: "form"}} do %>
    <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Browse pharmacy",
        data: {search_drugs_target: "input", action: "keyup->search-drugs#autocomplete"}
      %>
      <div class="d-grid gap-2 mt-3">
        <%= submit_tag "Search", class: "btn btn-success" %>
      </div>
    <% end %>
</div>







<div class="med-cards mt-3">
  <% @stocks.each do |stock| %>
    <% unless @medicine.name == stock.medicine.name %>
      <div class="card med-card">
        <%= cl_image_tag stock.medicine.photo.key, class: "med-card-img" %>
        <div>
          <h3><%= stock.medicine.name %></h3>
          <p class="med-card-price">Rs <%= number_with_delimiter(stock.medicine.price, :delimiter => ',') %></p>
          <% if stock.quantity == 0 %>
            <%= "Out of stock" %>
          <% else %>
            In stock: <%= stock.quantity %>
          <% end %>

          <%= simple_form_for([@pharmacy, @order]) do |f| %>
          <%= f.input :quantity, label: false, collection: 1..stock.quantity %>
          <%# <%= f.input :delivery %>
          <%= f.hidden_field :medicine_id, value: stock.medicine.id %>
          <%= f.submit value: "Add to cart", class: "btn btn-success" %>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>


<%= link_to 'Back', pharmacies_path(query: @query), class: "d-grid gap-2 btn btn-dark mt-4" %>
<div class="container mt-5" style="height: 10vh;"></div>