config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: :create
  end

  resources :pharmacies do
    resources :orders, only: [:create]
  end

  resources :medicines, only: :index

  resources :prescriptions, only: [:create]

  resources :orders, only: [:update, :show]

  get 'checkout', to: "pages#checkout", as: :checkout

  get 'profile', to: "pages#view_profile", as: :profile
end

app/views/pages/_upload_rx.html.erb
<%= simple_form_for(@prescription) do |f| %>
  <%= f.input :prescription, as: :file %>
  <%= f.submit value: "Upload" %>
<% end %>

app/views/pages/checkout.html.erb
<% if @order.present? %>
  <!-- Button trigger modal -->


  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Rx</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= render 'upload_rx' %>
        </div>
      </div>
    </div>
  </div>


  <h1>Checkout</h1>


  <div class="container-fluid">
    <div class="co-cards">

      <div class="co-card" data-bs-toggle="modal" data-bs-target="#exampleModal">
        <i class="mb-3 fa-solid fa-upload fa-3x"></i>
        <h3 class="mt-1">Upload Rx</h3>
      </div>


      <div class="co-card">
        <%= link_to chatroom_path(@chatroom) do %>
          <div class="text-center">
            <i class="mb-3 fa-solid fa-comment fa-3x"></i>
            <h3 class="mt-1">Talk to your pharmacist</h3>
          </div>
        <% end %>
      </div>
    </div>

    <%# <div class="co-cards">
      <%= simple_form_for(@order) do |f| %>
        <%# <%= f.radio_button :delivery, 0 %>
        <%# <%= label :delivery, 'Pickup', value: 1, class: "co-card" %>
        <%# <%= f.radio_button :delivery, 1 %>
        <%# <%= label :delivery, 'delivery', value: 0, class: "co-card" %>
        <%# <%= f.submit %>
      <%# <% end %>
    <%# </div> %>


    <p class="mt-3">Choose your delivery method:</p>
    <%= simple_form_for(@order) do |f| %>
    <div class="co-cards">
        <%= f.radio_button :delivery, 0 %>
        <%= f.label :delivery, 'Pickup', value: 0, class: "co-card co-card-del" do %>
          <i class="mb-3 fa-solid fa-shop fa-3x"></i>
          <h3 class="mt-1">Pickup</h3>
        <% end %>
        <%= f.radio_button :delivery, 1 %>
        <%= f.label :delivery, 'Delivery', value: 1, class: "co-card co-card-del" do %>
          <i class="mb-3 fa-solid fa-car-side fa-3x"></i>
          <h3 class="mt-1">Delivery</h3>
        <% end %>
      </div>
    <div class="d-grid gap-2 mt-3 btn-checkout">
      <%= f.submit 'Confirm', class: "btn btn-success" %>
    </div>

    <% end %>


  </div>
  <div class="container mt-5" style="height: 10vh;"></div>
<% else %>
<h4>No current order</h4>
<% end %>

app/views/pages/home.html.erb
<div class="align-items-center" id="home-banner">
  <%= image_tag("banner2.svg", class: "banner-img") %>
  <div class="banner-info">
    <h1><span>Med</span>Q</h1>
    <p>Pharmacy in your pocket</p>
  </div>
</div>

<div class="container-fluid features mt-4">
  <div class="card-feature">
    <i class="mb-3 fa-solid fa-upload fa-3x"></i>
    <p class="card-feature-text mt-1">Upload Rx</p>
  </div>
  <div class="card-feature">
    <i class="mb-3 fa-solid fa-comment fa-3x"></i>
    <p class="card-feature-text mt-1">Chat online</p>
  </div>
  <div class="card-feature mt-3">
    <i class="mb-3 fa-solid fa-shop fa-3x"></i>
    <p class="card-feature-text mt-1">Pick up</p>
  </div>
  <div class="card-feature mt-3">
    <i class="mb-3 fa-solid fa-car-side fa-3x"></i>
    <p class="card-feature-text mt-1">Get delivered</p>
  </div>
</div>

<div class="container-fluid mt-4">
  <div data-controller="search-drugs">
    <div class="form">
      <%= form_with url: pharmacies_path, method: :get, html: {data: {search_drugs_target: "form"}} do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Find your drug",
          data: {search_drugs_target: "input", action: "keyup->search-drugs#autocomplete"}
        %>
        <div class="d-grid gap-2 mt-3">
          <%= submit_tag "Search", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  <%# <%= render 'pharmacies/list', medicines: @medicines %>
  </div>
</div>

<div class="container-fluid py-2 mt-4">
    <h2 class="font-weight-light">News</h2>
    <div class="scrolling-wrapper">
        <div class="card card-body" id="home-card1">
        </div>
        <div class="card card-body" id="home-card2">
        </div>
        <div class="card card-body" id="home-card3">
        </div>
        <div class="card card-body" id="home-card4">
        </div>
        <div class="card card-body" id="home-card5">
        </div>
        <div class="card card-body" id="home-card6">
        </div>
        <div class="card card-body" id="home-card7">
        </div>
    </div>
</div>
<div class="container mt-5" style="height: 10vh;"></div>
<%# <% @medicines.each do |medicine| %>
  <%# <% if medicine.photo.attached? %>
    <%# <%= cl_image_tag medicine.photo.key, height: 300, width: 400, crop: :fill %>
  <%# <% end %>
<%# <% end %>

app/views/pages/view_profile.html.erb
<%= @user.email %>

<%= simple_form_for(@pharmacy) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :opening_hours %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit %>
<% end %>


<%= link_to chatroom_path(@chatroom) %>


<%# <% @chats.each do |chat| %> %>
<%# <%= @chatroom %> %>